# Generated by Django 4.1 on 2023-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_rec_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="images_out/")),
            ],
        ),
    ]
